language: go
dist: trusty
go_import_path: github.com/arthurkiller/perfM
sudo: false

go:
  - 1.6
  - 1.7.3

before_install:
   - go get github.com/Shopify/sarama
   - go get github.com/samuel/go-zookeeper/zk

script:
    - go build ./consumergroup/.
