language: go
dist: trusty
go_import_path: github.com/arthurkiller/perfM
sudo: false

go:
  - 1.5
  - 1.6
  - 1.7.3

env:
  global:
   - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64
   - TARGET=arm64
   - TARGET=arm
   - TARGET=386
   - TARGET=x86
   - TARGET=x64

before_install:
   - go get -v github.com/Shopify/sarama
   - go get -v github.com/samuel/go-zookeeper/zk

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  - go: tip
    env: TARGET=arm
  - go: tip
    env: TARGET=arm64
  - go: tip
    env: TARGET=386

script:
    - go build ./consumergroup/.
